spring:
  profiles:
    active: dev
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

  # 调用链 Sleuth + ZipKin
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采用比例，默认 0.1 全部采样 1.0
  zipkin:
    enabled: true
    base-url: http://192.168.135.1:9411/ # 指定了Zipkin服务器的地址
    discoveryClientEnabled: false
    sender:
      type: web