server:
  port: 8870

spring:
  application:
    name: sleuth-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos


# 调用链 Sleuth + ZipKin
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采用比例，默认 0.1 全部采样 1.0
  zipkin:
    enabled: true
    base-url: http://192.168.135.1:9411/ # 指定了Zipkin服务器的地址
    discoveryClientEnabled: false
    sender:
      #  数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据
      type: web
    service:
      name: ${spring.application.name}

# 查看sleuth详细日志
logging:
  level:
    org.springframework.cloud.sleuth: debug